### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by fhj39** [bossanova808/weather.ozweather#2]
Think you could do this up as a weather plugin?  =)
https://www.flightradar24.com/

**Comment by bossanova808** [comment]
For flight radar?  

I don't use it but the code is gpl, and a bunch of other folks have used it in different things like home automation and so on.  Go for it!

**Comment by bossanova808** [comment]
(It's already a weather plugin for Kodi in case I  misunderstand you)

**Comment by bossanova808** [comment]
Sorry - I am in idiot - you mean add flightradar 24 data to my mweather plugin?

**Comment by bossanova808** [comment]
Whilst I like the idea, I won't be doing this in a hurry - I think it's against their terms, but it's also not so feasible without a lot of work as there is no generated image to grab it seems - it's css icons overlaid on a google map, so I can't just go grab an image or whatever like I can with the BOM for example.

I can't find a free API for the data either.  If you can - let me know!
