### ISSUE TITLE
Update to 0.9 failed

### ISSUE THREAD

**Issue by kostaboxon** [bossanova808/weather.ozweather#3]
0.8.9 wont update to 0.9 due to dependancy script.module.urllib3 2.25.0 
(import addon="script.module.urllib3" version="2.25.0"/ ) ???
Addon still works. Jarvis and Krypton. Using LibreElec.

**Comment by bossanova808** [comment]
Well I'm not yet seeing the update here so I can't see it failing yet either (Kyrpton, Windows here) - but it should pull the dependency if it is not on your system already (Try uninstalling and re-installing - it may not pick up new dependencies on update perhaps?).  One that lib is in place it should work fine...as it does on my LE testbed at home...

**Comment by bossanova808** [comment]
JUST BTW - I had to add that to get the addon working with sub-profiles again.  It was fine on the master profile without it, but gave missing module errors on sub-profiles without the import.  Very weird...that's all I could work out that would fix it.

**Comment by kostaboxon** [comment]
Just uninstalled the add-on.
Tried to install 0.9 from repo ,
Failed with same Dependency notification.

**Comment by bossanova808** [comment]
ok - it's shown up here and I am getting the error too.  Annoying!

Pretty sure I stuffed up and got my urllib3 and python versions arse backwards - urllib3 is at 1.22 it seems - can you check what you have there just so I can be sure??

**Comment by kostaboxon** [comment]
I have the same urllib3  1.22

**Comment by bossanova808** [comment]
Thanks - I'll fix it up tonight & re-submit - should arrive in the next couple days, sorry for the whoopsie

**Comment by bossanova808** [comment]
Sorry I will do this tonight - I wanted to get more info and think I might know better now what was working (I think the requests lib or urllib3 is disabled in these sub profiles for some unknown reason).  I will investigate further tonight but either way will submit a fixed addon then.

**Comment by kostaboxon** [comment]
Confirming it is fixed. Installed from repo on one box and it updated on another.
Thank You

**Comment by bossanova808** [comment]
Yep - turns out there is a kodi bug that means new addons in sub profiles are installed in a disabled state by default...so addons that depend on those (or in this case use a library that in turn depends on them) -
 they crash.  So hopefully out of this kerfuffle will come a Kodi bugfix :)
