### ISSUE TITLE
LOGSEVERE and LOGNOTICE will deprecated in kodi/python addons

### ISSUE THREAD

**Issue by phunkyfish** [bossanova808/weather.ozweather#6]
Please replace with LOGFATAL and LOGINFO. They will be removed in a couple of weeks.

PR: https://github.com/xbmc/xbmc/pull/18346
Forum Post: https://forum.kodi.tv/showthread.php?tid=353818

**Comment by bossanova808** [comment]
Thanks, noted, & update will be submitted soon.
