### ISSUE TITLE
xbmc.translatePath is deprecated

### ISSUE THREAD

**Issue by heitbaum** [bossanova808/weather.ozweather#7]
Error with Kodi Matrix development (LibreELEC-Generic.x86_64-9.80-nightly-20201016-c5a4c7d.tar) and "CAddonMgr::FindAddons: weather.ozweather v1.2.1 installed"

2020-10-18 15:16:51.190 T:18647 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.

The reference if from: https://github.com/xbmc/xbmc/pull/17735

**Comment by bossanova808** [comment]
Sure, I will update this next time I submit an update...doesn't seem like it is worth an update on its own at this stage?

**Comment by heitbaum** [comment]
> Sure, I will update this next time I submit an update...doesn't seem like it is worth an update on its own at this stage?

100% agree - no rush. I have submitted a pull request. (In the throws of trying to get my test Kodi working again.... Since I moved on from Milhouse #0717. Its become a bit buggy.
